//! Frozen method names for THP JSON-RPC.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Method {
    Ping,
    Negotiate,
    Status,
    ScanStart,
    ScanStatus,
    ScanCancel,
    SearchTools,
    CapabilityList,
    RegistryCorrect,
    InspectTool,
    InspectInstance,
    ListEnvironments,
    ListDuplicates,
    ResolveCapability,
    ExecuteTool,
    ExecuteCancel,
    ApproveExecution,
    RevokeApproval,
    SkillList,
    SkillInspect,
    SkillResolve,
    DiscoveryStart,
    DiscoveryList,
    DiscoveryInspect,
    DiscoveryClassify,
    DiscoveryRevoke,
    AgentList,
    PolicyGet,
    PolicySet,
    ActivityList,
    ExportReport,
    ImportReport,
    RequestApproval,
    ListApprovals,
    SkillRegister,
    SettingsGet,
    SettingsSet,
    ResourceList,
    ResourceActivate,
    ResourceRollback,
    UpdateVerify,
    UpdateApply,
    UpdateCancel,
    AgentLaunch,
    AgentStatus,
    AgentCancel,
    CredentialsSet,
    CredentialsClear,
    CredentialsStatus,
    CredentialsSession,
    EventsSubscribe,
    EventsPoll,
    EventsUnsubscribe,
}

pub const METHOD_NAMES: &[(&str, Method)] = &[
    ("ping", Method::Ping),
    ("protocol.negotiate", Method::Negotiate),
    ("status", Method::Status),
    ("scan.start", Method::ScanStart),
    ("scan.status", Method::ScanStatus),
    ("scan.cancel", Method::ScanCancel),
    ("registry.search", Method::SearchTools),
    ("capability.list", Method::CapabilityList),
    ("registry.correct", Method::RegistryCorrect),
    ("registry.inspect_tool", Method::InspectTool),
    ("registry.inspect_instance", Method::InspectInstance),
    ("environment.list", Method::ListEnvironments),
    ("environment.duplicates", Method::ListDuplicates),
    ("resolve.capability", Method::ResolveCapability),
    ("execute.tool", Method::ExecuteTool),
    ("execute.cancel", Method::ExecuteCancel),
    ("execute.approve", Method::ApproveExecution),
    ("execute.revoke", Method::RevokeApproval),
    ("skill.list", Method::SkillList),
    ("skill.inspect", Method::SkillInspect),
    ("skill.resolve", Method::SkillResolve),
    ("discovery.start", Method::DiscoveryStart),
    ("discovery.list", Method::DiscoveryList),
    ("discovery.inspect", Method::DiscoveryInspect),
    ("discovery.classify", Method::DiscoveryClassify),
    ("discovery.revoke", Method::DiscoveryRevoke),
    ("agent.list", Method::AgentList),
    ("policy.get", Method::PolicyGet),
    ("policy.set", Method::PolicySet),
    ("activity.list", Method::ActivityList),
    ("export.report", Method::ExportReport),
    ("import.report", Method::ImportReport),
    ("execute.approval_request", Method::RequestApproval),
    ("execute.approvals", Method::ListApprovals),
    ("skill.register", Method::SkillRegister),
    ("settings.get", Method::SettingsGet),
    ("settings.set", Method::SettingsSet),
    ("resource.list", Method::ResourceList),
    ("resource.activate", Method::ResourceActivate),
    ("resource.rollback", Method::ResourceRollback),
    ("update.verify", Method::UpdateVerify),
    ("update.apply", Method::UpdateApply),
    ("update.cancel", Method::UpdateCancel),
    ("agent.launch", Method::AgentLaunch),
    ("agent.status", Method::AgentStatus),
    ("agent.cancel", Method::AgentCancel),
    ("credentials.set", Method::CredentialsSet),
    ("credentials.clear", Method::CredentialsClear),
    ("credentials.status", Method::CredentialsStatus),
    ("credentials.session", Method::CredentialsSession),
    ("events.subscribe", Method::EventsSubscribe),
    ("events.poll", Method::EventsPoll),
    ("events.unsubscribe", Method::EventsUnsubscribe),
];

impl Method {
    pub fn from_name(name: &str) -> Option<Method> {
        METHOD_NAMES
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, m)| *m)
    }
}
