import {useEffect,useState} from 'react'
import {invoke} from '@tauri-apps/api/core'
const rpc=(method:string,params:unknown={})=>invoke<any>('rpc',{method,params})
export default function ManagedTasks({notify}:{notify:(message:string)=>void}){
 const [tasks,setTasks]=useState<any[]>([]),[approvals,setApprovals]=useState<any[]>([]),[detail,setDetail]=useState<any>(null),[error,setError]=useState('')
 const load=async()=>{try{const [rows,pending]=await Promise.all([rpc('execute.list'),rpc('execute.approvals')]);setTasks(rows);setApprovals((Array.isArray(pending)?pending:pending.requests||[]).filter((a:any)=>a.status==='pending'&&a.body_available&&new Date(a.expires_at).getTime()>Date.now()))}catch(e){setError(String(e))}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),2000);return()=>clearInterval(timer)},[])
 const act=async(action:()=>Promise<any>)=>{try{await action();await load()}catch(e){setError(String(e))}}
 return <section className="card card-pad managed-tasks"><h3>工具执行任务</h3>{error&&<p className="muted">{error}</p>}{approvals.length>0&&<><h4>等待你的执行批准</h4>{approvals.map(a=><div className="program-draft" data-request-id={a.request_id||a.id} key={a.request_id||a.id}><code>{JSON.stringify(a.request||a,null,2)}</code><button className="btn" onClick={()=>void act(async()=>{await rpc('execute.approve',{request_id:a.request_id||a.id});notify('已批准此次执行，Agent 可继续调用')})}>批准此次执行</button></div>)}</>}{tasks.length===0&&<p className="muted">尚无工具执行任务。Agent 可提交经授权的后台任务，在这里查看状态。</p>}<ul className="list-clean">{tasks.map(t=><li key={t.execution_id}><div><strong>{t.name||t.instance_id}</strong><div className="muted">{({running:"运行中",success:"已完成",failed:"失败",cancelled:"已取消",interrupted:"重启中断",timed_out:"超时",denied:"已拒绝",expired:"已过期",unavailable:"不可用",invalid_request:"请求无效"} as Record<string,string>)[t.status]||t.status} · {t.duration_ms?Math.round(t.duration_ms/1000)+' 秒':t.started_at?new Date(t.started_at).toLocaleString():''}</div>{(t.artifacts||[]).map((a:any)=><button className="btn" key={a.path} onClick={()=>void act(()=>invoke('reveal_path',{path:a.path}))}>定位 {a.name}</button>)}</div><div className="program-actions"><button className="btn" onClick={()=>void act(async()=>setDetail(await rpc('execute.status',{execution_id:t.execution_id})))}>查看结果</button>{t.status==='running'&&<button className="btn" onClick={()=>void act(()=>rpc('execute.cancel',{execution_id:t.execution_id}))}>取消运行</button>}</div></li>)}</ul>{detail&&<div className="program-draft"><button className="btn" onClick={()=>setDetail(null)}>收起结果</button><pre style={{whiteSpace:'pre-wrap',wordBreak:'break-all',maxHeight:300,overflow:'auto'}}>{detail.result?JSON.stringify(detail.result,null,2):'输出未保留；状态：'+detail.status}</pre></div>}</section>
}
